
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Anshuman@108
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blog_app_development

  
test:
  <<: *default
  database: blog_app_test


production:
  <<: *default
  database: blog_app_production
  username: blog_app
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
